### ISSUE TITLE
Investigate issue397.jp2

### ISSUE THREAD

**Issue by quintusdias** [quintusdias/glymur#312]
```
jp2dump input/nonregression/issue397.jp2 
Traceback (most recent call last):
  File "/home/jevans/.local/bin/jp2dump", line 9, in <module>
    load_entry_point('Glymur==0.7.2', 'console_scripts', 'jp2dump')()
  File "/home/jevans/git/glymur/glymur/command_line.py", line 60, in main
    jp2 = Jp2k(filename)
  File "/home/jevans/git/glymur/glymur/jp2k.py", line 161, in __init__
    self.parse()
  File "/home/jevans/git/glymur/glymur/jp2k.py", line 295, in parse
    self._validate()
  File "/home/jevans/git/glymur/glymur/jp2k.py", line 302, in _validate
    if ftyp.brand == 'jp2 ':
AttributeError: 'UnknownBox' object has no attribute 'brand'
```

**Comment by quintusdias** [comment]
The problem occurs earlier than this, an undecodable compatibility list entry in the FileType box.  Just issue a warning.
