### ISSUE TITLE
warning tests broken on some versions of python-six, again

### ISSUE THREAD

**Issue by quintusdias** [quintusdias/glymur#314]
updated linux mint package has version 1.8.0, which evades the fixture trapping 1.6.x versions.  Results in error such as

```
======================================================================
ERROR: test_xml (glymur.test.test_printing.TestPrintingOpjDataRootWarns)
verify printing of XML box
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jevans/git/glymur/glymur/test/test_printing.py", line 884, in test_xml
    with self.assertWarns(UserWarning):
  File "/usr/lib/python3.4/unittest/case.py", line 203, in __enter__
    if getattr(v, '__warningregistry__', None):
  File "/usr/lib/python3/dist-packages/scipy/lib/six.py", line 116, in __getattr__
    _module = self._resolve()
  File "/usr/lib/python3/dist-packages/scipy/lib/six.py", line 105, in _resolve
    return _import_module(self.mod)
  File "/usr/lib/python3/dist-packages/scipy/lib/six.py", line 76, in _import_module
    __import__(name)
ImportError: No module named 'winreg'
```

**Comment by quintusdias** [comment]
The issue is not seen with six 1.7.3 on fedora 21

**Comment by quintusdias** [comment]
This issue is not seen with six 1.8.0 python 3.4.1 on opensuse 13.2

**Comment by quintusdias** [comment]
The issue is not seen on macports with six 1.8.0
