### ISSUE TITLE
run_tests method fails

### ISSUE THREAD

**Issue by quintusdias** [quintusdias/glymur#386]
```
======================================================================
ERROR: lib (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: lib
Traceback (most recent call last):
  File "/export/nco-lw-jevans2/jevans/anaconda3/envs/glymur_test/lib/python3.5/unittest/loader.py", line 462, in _find_test_path
    package = self._get_module_from_name(name)
  File "/export/nco-lw-jevans2/jevans/anaconda3/envs/glymur_test/lib/python3.5/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)
  File "/export/nco-lw-jevans2/jevans/git/glymur/glymur/lib/__init__.py", line 2, in <module>
    from . import openjp2 as openjp2
  File "/export/nco-lw-jevans2/jevans/git/glymur/glymur/lib/openjp2.py", line 10, in <module>
    from ..config import glymur_config
ValueError: attempted relative import beyond top-level package

```

Running the tests from the terminal in the usual way passes.

**Comment by quintusdias** [comment]
Issue is moot.  This code was removed.
