### ISSUE TITLE
Better error message needed if JP2C box cannot be parsed

### ISSUE THREAD

**Issue by quintusdias** [quintusdias/glymur#440]
```
UserWarning: Encountered an error while parsing a <class 'glymur.jp2box.ContiguousCodestreamBox'> box at byte offset 77.  The original error message was "Invalid codestream, expected to find a marker at byte position 17957.".
  warnings.warn(msg, UserWarning)
/Users/jevans/git/glymur/glymur/jp2box.py:254: UserWarning: b'jp2c' box may be invalid, the file pointer is positioned 16 bytes past the end of the box.
  warnings.warn(msg, UserWarning)
/Users/jevans/git/glymur/glymur/jp2box.py:171: UserWarning: Unrecognized box (b'\xb4\xea\xa0P') encountered at byte offset 17943.
  warnings.warn(msg, UserWarning)
/Users/jevans/git/glymur/glymur/jp2box.py:246: UserWarning: b'\xb4\xea\xa0P' box has incorrect box length (2505318516)
  warnings.warn(msg)
Traceback (most recent call last):
  File "doit.py", line 13, in <module>
    j = glymur.Jp2k(file)
  File "/Users/jevans/git/glymur/glymur/jp2k.py", line 172, in __init__
    self.parse()
  File "/Users/jevans/git/glymur/glymur/jp2k.py", line 322, in parse
    self._validate()
  File "/Users/jevans/git/glymur/glymur/jp2k.py", line 355, in _validate
    segment for segment in self.codestream.segment
  File "/Users/jevans/git/glymur/glymur/jp2k.py", line 238, in codestream
    self._codestream = self.get_codestream(header_only=True)
  File "/Users/jevans/git/glymur/glymur/jp2k.py", line 1437, in get_codestream
    fptr.seek(box[0].offset)
IndexError: list index out of range
```

**Comment by quintusdias** [comment]
commit 1a1e50553936638cb8474e58561847b6320c246d (HEAD -> devel)
Author: John Evans <john.g.evans.ne@gmail.com>
Date:   Sat Mar 3 16:49:44 2018 -0500

    Issue error if a valid JP2/JP2C box is not found
    
    Closes-Issue: #440
