### ISSUE TITLE
Better error message needed when no JP2/IHDR box is found

### ISSUE THREAD

**Issue by quintusdias** [quintusdias/glymur#441]
```
/Users/jevans/git/openjpeg-data/input/nonregression/issue364-903.jp2
/Users/jevans/git/glymur/glymur/jp2box.py:171: UserWarning: Unrecognized box (b'ihdi') encountered at byte offset 40.
  warnings.warn(msg, UserWarning)
Traceback (most recent call last):
  File "doit.py", line 13, in <module>
    j = glymur.Jp2k(file)
  File "/Users/jevans/git/glymur/glymur/jp2k.py", line 172, in __init__
    self.parse()
  File "/Users/jevans/git/glymur/glymur/jp2k.py", line 322, in parse
    self._validate()
  File "/Users/jevans/git/glymur/glymur/jp2k.py", line 357, in _validate
    ihdr_dims = ihdr.height, ihdr.width, ihdr.num_components
AttributeError: 'UnknownBox' object has no attribute 'height'
```

**Comment by quintusdias** [comment]
No more action planned.
