### ISSUE TITLE
jp2dump fails on s2tbx file

### ISSUE THREAD

**Issue by quintusdias** [quintusdias/glymur#444]
```
$ jp2dump /Users/jevans/git/s2tbx/s2tbx-reader/src/test/resources/org/esa/s2tbx/dataio/s2/l1c/IMG_GPPL1C_054_20091210235100_20091210235130_02_000000_15SUC.jp2
Traceback (most recent call last):
  File "/Users/jevans/anaconda3/envs/cforge/bin/jp2dump", line 6, in <module>
    sys.exit(glymur.command_line.main())
  File "/Users/jevans/git/glymur/glymur/command_line.py", line 61, in main
    jp2 = Jp2k(filename)
  File "/Users/jevans/git/glymur/glymur/jp2k.py", line 179, in __init__
    self.parse()
  File "/Users/jevans/git/glymur/glymur/jp2k.py", line 301, in parse
    signature, = struct.unpack('>H', read_buffer)
struct.error: unpack requires a buffer of 2 bytes
```

**Comment by quintusdias** [comment]
No action needed.   The file is zero bytes.
