### ISSUE TITLE
Confusing error message from test suite regarding flst boxes

### ISSUE THREAD

**Issue by quintusdias** [quintusdias/glymur#470]
```
======================================================================
ERROR: test_flst_lens_not_the_same (tests.test_jp2box_jpx.TestJPX)
A fragment list box items must be the same length.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/jevans/git/glymur/tests/test_jp2box_jpx.py", line 467, in test_flst_lens_not_the_same
    flst.write(tfile)
  File "/Users/jevans/git/glymur/glymur/jp2box.py", line 1389, in write
    self._validate(writing=True)
  File "/Users/jevans/git/glymur/glymur/jp2box.py", line 1352, in _validate
    self._dispatch_validation_error(msg, writing=writing)
  File "/Users/jevans/git/glymur/glymur/jp2box.py", line 103, in _dispatch_validation_error
    raise IOError(msg)
OSError: The lengths of the fragment offsets (1),fragment lengths (1), and data reference items (2) must be the same.
```

**Comment by quintusdias** [comment]
commit 61d508d918a66583be744fcf0e4b0866171bafca (HEAD -> LTS, origin/LTS)
Author: John Evans <john.g.evans.ne@gmail.com>
Date:   Fri Apr 5 15:32:01 2019 -0400

    Improve FragmentListBox warning, error messages
    
    Update a FragmentListBox test to verify warnings as well as errors.
