### ISSUE TITLE
Test errors when looking at new openjpeg library 2.3.1

### ISSUE THREAD

**Issue by quintusdias** [quintusdias/glymur#476]
These seem to be problems with the test suite, rather than actual issues.

```
======================================================================
FAIL: test_anaconda_on_mac (tests.test_config.TestSuite)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/mock.py", line 1204, in patched
    return func(*args, **keywargs)
  File "/Users/jevans/git/glymur/tests/test_config.py", line 57, in test_anaconda_on_mac
    self.assertEqual(actual, expected)
AssertionError: PosixPath('/opt/openjpeg-2.3.1/lib/libopenjp2.dylib') != PosixPath('/opt/anaconda/lib/libopenjp2.dylib')

======================================================================
FAIL: test_not_via_ctypes (tests.test_config.TestSuite)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/mock.py", line 1204, in patched
    return func(*args, **keywargs)
  File "/Users/jevans/git/glymur/tests/test_config.py", line 129, in test_not_via_ctypes
    self.assertIsNone(actual)
AssertionError: <CDLL '/opt/openjpeg-2.3.1/lib/libopenjp2.dylib', handle 7fe9a3814260 at 0x10aff1940> is not None

======================================================================
FAIL: test_via_ctypes (tests.test_config.TestSuite)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/mock.py", line 1204, in patched
    return func(*args, **keywargs)
  File "/Users/jevans/git/glymur/tests/test_config.py", line 111, in test_via_ctypes
    self.assertEqual(actual, expected)
AssertionError: PosixPath('/opt/openjpeg-2.3.1/lib/libopenjp2.dylib') != PosixPath('/usr/lib/libopenjp2.so')

======================================================================
FAIL: test_config_file_in_current_directory (tests.test_config.TestSuiteConfigFile)
A configuration file in the current directory should be honored.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/jevans/git/glymur/tests/test_config.py", line 304, in test_config_file_in_current_directory
    self.assertEqual(glymur.lib.openjp2.OPENJP2._name, libloc)
AssertionError: PosixPath('/opt/openjpeg-2.3.1/lib/libopenjp2.dylib') != PosixPath('/opt/local/lib/libopenjp2.dylib')
```

**Comment by quintusdias** [comment]
commit 608528697d2bdefbe186e687e937622ee80295ca (HEAD -> devel, origin/issue476, issue476)
Author: John Evans <john.g.evans.ne@gmail.com>
Date:   Thu Apr 4 10:23:21 2019 -0400

    Fix broken tests when config file is actively used
    
    If a configuration file was being actively used, some tests would fail
    because different code paths were being taken than what was assumed
    by the tests.  Force the assumed code path and fix the issue by adding
    another patcher that prevents a configuration file from being found.
