### ISSUE TITLE
Using python2 on glymur>=0.9 should result in informative error message

### ISSUE THREAD

**Issue by quintusdias** [quintusdias/glymur#484]
Right now we get 

```
>>> import glymur
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "glymur/__init__.py", line 4, in <module>
    from glymur import version
  File "glymur/version.py", line 49
    """
      ^
SyntaxError: invalid syntax
```

**Comment by quintusdias** [comment]
no action planned
