### ISSUE TITLE
Test failure on windows with bad library location

### ISSUE THREAD

**Issue by quintusdias** [quintusdias/glymur#504]
```
(base) C:\Users\jevan\Documents\glymur>python -m unittest tests.test_warnings.TestConfigurationWarnings.test_xdg_env_config_file_is_bad
C:\Users\jevan\Anaconda3\lib\site-packages\pyreadline\py3k_compat.py:8: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3,and in 3.9 it will stop working
  return isinstance(x, collections.Callable)
> c:\users\jevan\documents\glymur\tests\test_warnings.py(904)test_xdg_env_config_file_is_bad()
-> lib_path = self.test_dir_path / 'libopenjp2.dylib.not.there'
(Pdb) c
E
======================================================================
ERROR: test_xdg_env_config_file_is_bad (tests.test_warnings.TestConfigurationWarnings)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\jevan\Documents\glymur\glymur\config.py", line 143, in glymur_config
    opj_lib = loader(path)
  File "C:\Users\jevan\Anaconda3\lib\ctypes\__init__.py", line 442, in LoadLibrary
    return self._dlltype(name)
  File "C:\Users\jevan\Anaconda3\lib\ctypes\__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
TypeError: LoadLibrary() argument 1 must be str, not WindowsPath

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\jevan\Documents\glymur\tests\test_warnings.py", line 904, in test_xdg_env_config_file_is_bad
    lib_path = self.test_dir_path / 'libopenjp2.dylib.not.there'
  File "C:\Users\jevan\Anaconda3\lib\imp.py", line 314, in reload
    return importlib.reload(module)
  File "C:\Users\jevan\Anaconda3\lib\importlib\__init__.py", line 169, in reload
    _bootstrap._exec(spec, module)
  File "<frozen importlib._bootstrap>", line 630, in _exec
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\jevan\Documents\glymur\glymur\lib\openjp2.py", line 13, in <module>
    OPENJP2 = glymur_config()
  File "C:\Users\jevan\Documents\glymur\glymur\config.py", line 148, in glymur_config
    opj_lib = loader(path)
  File "C:\Users\jevan\Anaconda3\lib\ctypes\__init__.py", line 442, in LoadLibrary
    return self._dlltype(name)
  File "C:\Users\jevan\Anaconda3\lib\ctypes\__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 193] %1 is not a valid Win32 application

----------------------------------------------------------------------
Ran 1 test in 4.470s

FAILED (errors=1)
```

**Comment by quintusdias** [comment]
```
commit 326da885bd25abdc61bc0916982474dfcfb0815c (HEAD -> devel, origin/devel, issue504)
Author: John Evans <john.g.evans.ne@gmail.com>
Date:   Sun Jan 5 15:22:24 2020 -0800

    Skip bad library location test point on windows

    If the configuration file points to a bad library location, the result
    is different on Windows than on mac/linux.  On mac/linux, there is a
    warning.  On windows, there is an OSError raised, with a pop-up window
    hindering the test point.

    Since this is something of an edge case now with Anaconda being so
    prevalent, I think it is ok to just skip this test on windows.
```
