### ISSUE TITLE
test point failure on windows involving soft link

### ISSUE THREAD

**Issue by quintusdias** [quintusdias/glymur#505]
```
======================================================================
ERROR: test_config_file_in_current_directory (tests.test_config.TestSuiteConfigFile)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\jevan\Documents\glymur\tests\test_config.py", line 313, in test_config_file_in_current_directory
    new_library_path.symlink_to(existing_library)
  File "C:\Users\jevan\Anaconda3\lib\pathlib.py", line 1337, in symlink_to
    self._accessor.symlink(target, self, target_is_directory)
OSError: symbolic link privilege not held
```

**Comment by quintusdias** [comment]
```
commit 5204f62528a4bc66898e9a7d0ec1fe8222cadb48 (HEAD -> devel, issue505)
Author: John Evans <john.g.evans.ne@gmail.com>
Date:   Sun Jan 5 16:12:42 2020 -0800

    Skip config file test on windows

    The test for having a config file in the current directory is
    problematic on windows.  In order to really test this, we need to create
    an entry for the library that is named differently than the "system"
    library path name.  This can be done on mac/linux easily with a symlink,
    but this is problematic on windows as it seems to involve elevated
    privileges.  Same with just copying the library.  Again, since config
    files are getting a bit deprecated, I think it's ok to just skip this on
    windows.
```
