### ISSUE TITLE
tiff2jp2k fails on JWST TIFF

### ISSUE THREAD

**Issue by quintusdias** [quintusdias/glymur#555]
```
tiff2jp2 --tilesize 2048 2048 ~/Downloads/STScI-01G7DAXJYYTYXCFSB8VQRK5X2F.tif a.jp2
Traceback (most recent call last):
  File "/Users/jevans/anaconda3/envs/cforge/bin/tiff2jp2", line 10, in <module>
    sys.exit(tiff2jp2())
  File "/Users/jevans/git/jevans/glymur/glymur/command_line.py", line 176, in tiff2jp2
    j.run()
  File "/Users/jevans/git/jevans/glymur/glymur/tiff.py", line 96, in run
    self.copy_metadata()
  File "/Users/jevans/git/jevans/glymur/glymur/tiff.py", line 126, in copy_metadata
    uuid_box = UUIDBox(uuid, payload, box_length)
  File "/Users/jevans/git/jevans/glymur/glymur/jp2box.py", line 3407, in __init__
    self._parse_raw_data()
  File "/Users/jevans/git/jevans/glymur/glymur/jp2box.py", line 3433, in _parse_raw_data
    self.data = tiff_header(payload)
  File "/Users/jevans/git/jevans/glymur/glymur/_tiff.py", line 34, in tiff_header
    exif = ExifImageIfd(endian, read_buffer, offset)
  File "/Users/jevans/git/jevans/glymur/glymur/_tiff.py", line 460, in __init__
    self.post_process(self.tagnum2name)
  File "/Users/jevans/git/jevans/glymur/glymur/_tiff.py", line 158, in post_process
    ifd = ExifImageIfd(self.endian, self.read_buffer, value)
  File "/Users/jevans/git/jevans/glymur/glymur/_tiff.py", line 459, in __init__
    super().__init__(endian, read_buffer, offset)
  File "/Users/jevans/git/jevans/glymur/glymur/_tiff.py", line 86, in __init__
    self.num_tags, = struct.unpack(
struct.error: unpack requires a buffer of 2 bytes
```

**Comment by quintusdias** [comment]
The first IFD is at byte offset 8 with 24 tags, so that means that the 1st IFD spans only 288 bytes.  
The Exif IFD is at byte offset 42562 with 7 tags, so that means 84 bytes.

So we have a problem creating a UUIDBox from the TIFF metadata if there is an ExifTag
