### ISSUE TITLE
error writing big jp2 file from tiff

### ISSUE THREAD

**Issue by quintusdias** [quintusdias/glymur#665]
The TIFF directory is as follows:

```
=== TIFF directory 0 ===
TIFF Directory at offset 0x6c746e8 (113723112)
  Subfile Type: (0 = 0x0)
  Image Width: 17927 Image Length: 20273 Image Depth: 1
  Tile Width: 240 Tile Length: 240
  Bits/Sample: 8
  Compression Scheme: JPEG
  Photometric Interpretation: RGB color
  YCbCr Subsampling: 2, 2
  Samples/Pixel: 3
  Planar Configuration: single image plane
  ImageDescription: Aperio Image Library vFS90 01
18288x20373 [0,100 17927x20273] (240x240) JPEG/RGB Q=70|AppMag = 20|StripeWidth = 2032|ScanScope ID = SS1598|Filename = 14112|Date = 10/25/11|Time = 14:13:22|Time Zone = GMT+09:00|User = 354dc22c-fa1f-4941-a1b4-8df81657cb01|MPP = 0.4962|Left = 34.280785|Top = 19.041689|LineCameraSkew = 0.000320|LineAreaXOffset = 0.060417|LineAreaYOffset = 0.011084|Focus Offset = -0.000500|DSR ID = ap6101-dsr|ImageID = 14112|Exposure Time = 109|Exposure Scale = 0.000001|DisplayColor = 0|OriginalWidth = 18288|OriginalHeight = 20373|ICC Profile = ScanScope v1
  JPEG Tables: (289 bytes)
```

The error comes after writing tile 80

```
Writing tile 80
Writing tile 81
Traceback (most recent call last):
  File "/Users/jevans/anaconda3/envs/cforge/bin/tiff2jp2", line 10, in <module>
    sys.exit(tiff2jp2())
             ^^^^^^^^^^
  File "/Users/jevans/anaconda3/envs/cforge/lib/python3.12/site-packages/glymur/command_line.py", line 233, in tiff2jp2
    j.run()
  File "/Users/jevans/anaconda3/envs/cforge/lib/python3.12/site-packages/glymur/tiff.py", line 209, in run
    self.copy_image()
  File "/Users/jevans/anaconda3/envs/cforge/lib/python3.12/site-packages/glymur/tiff.py", line 730, in copy_image
    self._write_tiled_tiff_to_tiled_jp2k()
  File "/Users/jevans/anaconda3/envs/cforge/lib/python3.12/site-packages/glymur/tiff.py", line 845, in _write_tiled_tiff_to_tiled_jp2k
    tilewriter[:] = jp2k_tile
    ~~~~~~~~~~^^^
  File "/Users/jevans/anaconda3/envs/cforge/lib/python3.12/site-packages/glymur/jp2k.py", line 1379, in __setitem__
    raise e
  File "/Users/jevans/anaconda3/envs/cforge/lib/python3.12/site-packages/glymur/jp2k.py", line 1367, in __setitem__
    opj2.write_tile(
  File "/Users/jevans/anaconda3/envs/cforge/lib/python3.12/site-packages/glymur/lib/openjp2.py", line 1486, in write_tile
    OPENJP2.opj_write_tile(
  File "/Users/jevans/anaconda3/envs/cforge/lib/python3.12/site-packages/glymur/lib/openjp2.py", line 591, in check_error
    raise OpenJPEGLibraryError(msg)
glymur.lib.openjp2.OpenJPEGLibraryError: OpenJPEG library error:  Size mismatch between tile data and sent data.
```

**Comment by quintusdias** [comment]
It happens when single-threaded, so should be reproducible with smaller files.
